### ISSUE TITLE
float*Vector3 throw an error "attempt to index a function value" on ios

### ISSUE THREAD

**Issue by whutlee** [pangweiwei/slua#142]
`local ret=3*Vector.up`

**Comment by Magicqy** [comment]
Change to:  Vector.up * 3

**Comment by whutlee** [comment]
but 3*Vector.up can work when use lua implemented valuetype,so some code may cause error on ios but can work on android

**Comment by pangweiwei** [comment]
valuetype code like vector3,vector4 etc are not same completely

valuetype code implemented by lua on android because that luajit is enabled, but implemented by c# on iOS because that luajit is disabled. If luajit is disabled, valuetype implemented by c# is faster than lua, so slua auto switch valuetype implement on different OS
